"""add water quality measurements

Revision ID: 31bde48bed6c
Revises: b660ddf29932
Create Date: 2026-09-14 20:03:50.102489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31bde48bed6c'
down_revision: Union[str, Sequence[str], None] = 'b660ddf29932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_quality_measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pond_id', sa.Uuid(), nullable=False),
    sa.Column('parameter', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], name='fk_water_quality_pond_id_ponds'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_water_quality_pond_measured_at', 'water_quality_measurements', ['pond_id', 'measured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_water_quality_pond_measured_at', table_name='water_quality_measurements')
    op.drop_table('water_quality_measurements')
    # ### end Alembic commands ###
