"""add stocking records

Revision ID: 3578a606a2a9
Revises: c490add02e9c
Create Date: 2026-09-14 20:07:48.500410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3578a606a2a9'
down_revision: Union[str, Sequence[str], None] = 'c490add02e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocking_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pond_id', sa.Uuid(), nullable=False),
    sa.Column('species_id', sa.Uuid(), nullable=False),
    sa.Column('stocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('initial_average_weight_g', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], name='fk_stocking_pond_id_ponds'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name='fk_stocking_species_id_species'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stocking_pond_stocked_at', 'stocking_records', ['pond_id', 'stocked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stocking_pond_stocked_at', table_name='stocking_records')
    op.drop_table('stocking_records')
    # ### end Alembic commands ###
