"""add health events

Revision ID: 4c89fe257343
Revises: 55e237b14e63
Create Date: 2026-09-14 20:10:19.838468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c89fe257343'
down_revision: Union[str, Sequence[str], None] = '55e237b14e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pond_id', sa.Uuid(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('mortality_count', sa.Integer(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], name='fk_health_pond_id_ponds'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_pond_observed_at', 'health_events', ['pond_id', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_pond_observed_at', table_name='health_events')
    op.drop_table('health_events')
    # ### end Alembic commands ###
