"""add growth records

Revision ID: 55e237b14e63
Revises: 3578a606a2a9
Create Date: 2026-09-14 20:09:05.755198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e237b14e63'
down_revision: Union[str, Sequence[str], None] = '3578a606a2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growth_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pond_id', sa.Uuid(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('average_weight_g', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('estimated_biomass_kg', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], name='fk_growth_pond_id_ponds'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_growth_pond_sampled_at', 'growth_records', ['pond_id', 'sampled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_growth_pond_sampled_at', table_name='growth_records')
    op.drop_table('growth_records')
    # ### end Alembic commands ###
