"""link ponds to species

Revision ID: 8f41baf28c35
Revises: 7cb484811cdf
Create Date: 2026-09-14 19:58:45.763139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f41baf28c35'
down_revision: Union[str, Sequence[str], None] = '7cb484811cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ponds', sa.Column('species_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_ponds_species_id'), 'ponds', ['species_id'], unique=False)
    op.create_foreign_key('fk_ponds_species_id_species', 'ponds', 'species', ['species_id'], ['id'])
    op.drop_column('ponds', 'species')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ponds', sa.Column('species', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint('fk_ponds_species_id_species', 'ponds', type_='foreignkey')
    op.drop_index(op.f('ix_ponds_species_id'), table_name='ponds')
    op.drop_column('ponds', 'species_id')
    # ### end Alembic commands ###
