"""add farm configuration fields

Revision ID: b660ddf29932
Revises: da294af3ef2e
Create Date: 2026-09-14 20:01:54.725032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b660ddf29932'
down_revision: Union[str, Sequence[str], None] = 'da294af3ef2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('farm_type', sa.String(length=100), nullable=True))
    op.add_column('farms', sa.Column('total_area_m2', sa.Float(), nullable=True))
    op.add_column('farms', sa.Column('water_source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'water_source')
    op.drop_column('farms', 'total_area_m2')
    op.drop_column('farms', 'farm_type')
    # ### end Alembic commands ###
