"""add harvest records

Revision ID: baef2b0caec0
Revises: 4c89fe257343
Create Date: 2026-09-14 20:11:43.192958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baef2b0caec0'
down_revision: Union[str, Sequence[str], None] = '4c89fe257343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harvest_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pond_id', sa.Uuid(), nullable=False),
    sa.Column('harvested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('average_weight_g', sa.Float(), nullable=True),
    sa.Column('survival_rate', sa.Float(), nullable=True),
    sa.Column('selling_price_per_kg', sa.Float(), nullable=True),
    sa.Column('buyer', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], name='fk_harvest_pond_id_ponds'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_harvest_pond_harvested_at', 'harvest_records', ['pond_id', 'harvested_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_harvest_pond_harvested_at', table_name='harvest_records')
    op.drop_table('harvest_records')
    # ### end Alembic commands ###
