"""add feeding records

Revision ID: c490add02e9c
Revises: 31bde48bed6c
Create Date: 2026-09-14 20:05:55.580740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c490add02e9c'
down_revision: Union[str, Sequence[str], None] = '31bde48bed6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeding_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pond_id', sa.Uuid(), nullable=False),
    sa.Column('feed_type', sa.String(length=100), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('fed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], name='fk_feeding_pond_id_ponds'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feeding_pond_fed_at', 'feeding_records', ['pond_id', 'fed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feeding_pond_fed_at', table_name='feeding_records')
    op.drop_table('feeding_records')
    # ### end Alembic commands ###
