"""harden domain indexes

Revision ID: d4791660f688
Revises: baef2b0caec0
Create Date: 2026-09-14 20:13:43.415671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4791660f688'
down_revision: Union[str, Sequence[str], None] = 'baef2b0caec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_farms_owner_name', 'farms', ['owner_id', 'name'], unique=False)
    op.create_index('ix_ponds_farm_name', 'ponds', ['farm_id', 'name'], unique=False)
    op.create_index('ix_species_category', 'species', ['category'], unique=False)
    op.create_index('ix_species_common_name', 'species', ['common_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_species_common_name', table_name='species')
    op.drop_index('ix_species_category', table_name='species')
    op.drop_index('ix_ponds_farm_name', table_name='ponds')
    op.drop_index('ix_farms_owner_name', table_name='farms')
    # ### end Alembic commands ###
