"""add pond configuration fields

Revision ID: da294af3ef2e
Revises: 8f41baf28c35
Create Date: 2026-09-14 20:00:15.761245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da294af3ef2e'
down_revision: Union[str, Sequence[str], None] = '8f41baf28c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ponds', sa.Column('depth_m', sa.Float(), nullable=True))
    op.add_column('ponds', sa.Column('culture_type', sa.String(length=100), nullable=True))
    op.add_column('ponds', sa.Column('water_source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ponds', 'water_source')
    op.drop_column('ponds', 'culture_type')
    op.drop_column('ponds', 'depth_m')
    # ### end Alembic commands ###
